### ISSUE TITLE
Image filtering for multi-channel images

### ISSUE THREAD

**Issue by nicholas512** [jblindsay/whitebox-geospatial-analysis-tools#56] opened 2019-01-29 14:59 UTC
[Feature Request]: When I run, for example, `wbt.lee_filter()` on a tif with two bands, the resulting tif has only one band has visible banding. It would be a nice feature to be able to run the filter on the original tif instead of having to split it up, filter each band individually, and then re-stack them.

![image](https://user-images.githubusercontent.com/15223327/51916972-75403500-23ac-11e9-896c-faa688018a29.png)

![image](https://user-images.githubusercontent.com/15223327/51916903-4de96800-23ac-11e9-9ef2-02d2fd0a8c81.png)

**Comment by jblindsay** [comment] 2019-01-29 15:11
First, I think that this issue is intended for the [WhiteboxTools](https://github.com/jblindsay/whitebox-tools) project and not the Whitebox GAT project. As such, I am closing this issue as off-topic. The root cause of your issue, however, is that WhiteboxTools does not currently support writing multi-band TIFFs. The TIFF format is extremely flexible and the WhiteboxTools encoder/decoder is a hand-rolled implementation that still requires some work to get to the point of maturity. I'm only one person working on this codebase and frankly I could spend my entire time coding just the GeoTIFF support in WhiteboxTools. GeoTIFF are just too flexible.

**Closed by jblindsay** 2019-01-29 15:11 UTC

**Comment by nicholas512** [comment] 2019-02-04 18:45
Thanks for the response, John!  This was indeed intended for WhiteboxTools, thanks for clarifying that.  I can appreciate all the hard work that has gone into this project so far, and did not realize just how much goes into the GeoTIFF side of things.
